"""Initial tables

Revision ID: 036f1961c018
Revises: 
Create Date: 2026-06-01 14:49:15.010783
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '036f1961c018'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('day',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('state', sa.Enum('OPEN', 'CLOSE', name='daystate'), nullable=False),
    sa.Column('euro_list', sa.Text(), nullable=True),
    sa.Column('euro_total', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('date')
    )
    op.create_table('epic',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=30), nullable=False),
    sa.Column('description', sa.String(length=100), nullable=True),
    sa.Column('type', sa.String(length=30), nullable=True),
    sa.Column('deposit', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('position',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('epic', sa.String(length=30), nullable=False),
    sa.Column('epic_name', sa.String(length=10), nullable=False),
    sa.Column('deal_reference', sa.String(length=30), nullable=True),
    sa.Column('fix_open', sa.Integer(), nullable=True),
    sa.Column('fix_close', sa.Integer(), nullable=True),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('time_open', sa.Time(), nullable=True),
    sa.Column('time_close', sa.Time(), nullable=True),
    sa.Column('time_open_broker', sa.Time(), nullable=True),
    sa.Column('time_close_broker', sa.Time(), nullable=True),
    sa.Column('state', sa.Enum('OPEN', 'CLOSE', name='positionstate'), nullable=False),
    sa.Column('strategy', sa.Enum('TARGET', 'FINISH', name='positionstrategy'), nullable=True),
    sa.Column('level_follower', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('level_win', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('level_zero', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('level_open', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('level_loose', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('level_security', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('level_close', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('level_stop', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('pip_spread', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('reason_close', sa.String(length=30), nullable=True),
    sa.Column('size', sa.Integer(), nullable=True),
    sa.Column('negative', sa.Integer(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('win', sa.Integer(), nullable=True),
    sa.Column('stop_update', sa.Integer(), nullable=True),
    sa.Column('euro', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('euro_stop', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('euro_max', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('euro_min', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('resume',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('epic', sa.String(length=30), nullable=False),
    sa.Column('day', sa.Date(), nullable=True),
    sa.Column('week', sa.String(length=10), nullable=True),
    sa.Column('direction', sa.String(length=10), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('resume', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_resume_epic'), ['epic'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('resume', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_resume_epic'))

    op.drop_table('resume')
    op.drop_table('position')
    op.drop_table('epic')
    op.drop_table('day')
    # ### end Alembic commands ###
